/*
 * WSO2 API Manager - Store
 * This document specifies a **RESTful API** for WSO2 **API Manager** - Store.  It is written with [swagger 2](http://swagger.io/). 
 *
 * OpenAPI spec version: v1.0
 * Contact: architecture@wso2.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.wso2.carbon.apimgt.rest.integration.tests.store.api;

import org.testng.Assert;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;
import org.wso2.carbon.apimgt.rest.integration.tests.store.ApiException;
import org.wso2.carbon.apimgt.rest.integration.tests.store.common.SampleTestObjectCreator;
import org.wso2.carbon.apimgt.rest.integration.tests.store.model.API;
import org.wso2.carbon.apimgt.rest.integration.tests.store.model.Comment;
import org.wso2.carbon.apimgt.rest.integration.tests.store.model.Document;
import org.wso2.carbon.apimgt.rest.integration.tests.store.model.DocumentList;
import org.wso2.carbon.apimgt.rest.integration.tests.store.model.Rating;
import org.wso2.carbon.apimgt.rest.integration.tests.store.model.RatingList;

import java.util.UUID;

/**
 * API tests for APIIndividualApi
 */
public class APIIndividualApiTest {

    private final APIIndividualApi api = new APIIndividualApi();
    private final org.wso2.carbon.apimgt.rest.integration.tests.publisher.api.APICollectionApi apiSetup =
            new org.wso2.carbon.apimgt.rest.integration.tests.publisher.api.APICollectionApi();
    private final org.wso2.carbon.apimgt.rest.integration.tests.publisher.api.APIIndividualApi apiRemove =
            new org.wso2.carbon.apimgt.rest.integration.tests.publisher.api.APIIndividualApi();
    SampleTestObjectCreator sampleTestObjectCreator = new SampleTestObjectCreator();

    private org.wso2.carbon.apimgt.rest.integration.tests.publisher.model.API response1 = null;
    private String generatedCommentId = UUID.randomUUID().toString();
    ;

    @BeforeClass
    public void beforeClass() throws org.wso2.carbon.apimgt.rest.integration.tests.publisher.ApiException {
        org.wso2.carbon.apimgt.rest.integration.tests.publisher.model.API api001 = sampleTestObjectCreator.createSampleAPI("api001", "api001", "1.0.0",
                "admin", "CREATED");
        response1 = apiSetup.apisPost(api001, "application/json");
        apiRemove.apisChangeLifecyclePost("Published", response1.getId(), null, null, null);
    }

    /**
     * Remove a Comment
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apisApiIdCommentsCommentIdDeleteTest() throws ApiException {
        String commentId = UUID.randomUUID().toString();
        String apiId = response1.getId();
        String commentText = "This is a comment";
        String ifNoneMatch = null;
        String ifModifiedSince = null;
        String ifMatch = null;
        String ifUnmodifiedSince = null;

        Comment body = new Comment();
        body.setCommentId(commentId);
        body.setApiId(apiId);
        body.setUsername(response1.getProvider());
        body.setCommentText(commentText);

        Comment responseCommpentPost = api.apisApiIdCommentsPost(apiId, body);
        Comment responseCommentGet = api.apisApiIdCommentsCommentIdGet
                (responseCommpentPost.getCommentId(), apiId, ifNoneMatch, ifModifiedSince);

        api.apisApiIdCommentsCommentIdDelete(responseCommentGet.getCommentId(), apiId, ifMatch, ifUnmodifiedSince);
    }

    /**
     * Get the individual comment given by a username for a certain API.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apisApiIdCommentsCommentIdGetTest() throws ApiException {
        String commentId = UUID.randomUUID().toString();
        String apiId = response1.getId();
        String commentText = "This is a comment";
        String ifNoneMatch = null;
        String ifModifiedSince = null;

        Comment body = new Comment();
        body.setCommentId(commentId);
        body.setApiId(apiId);
        body.setUsername(response1.getProvider());
        body.setCommentText(commentText);

        Comment responseCommpentPost = api.apisApiIdCommentsPost(apiId, body);
        Comment response = api.apisApiIdCommentsCommentIdGet
                (responseCommpentPost.getCommentId(), apiId, ifNoneMatch, ifModifiedSince);

        Assert.assertEquals(response.getCommentText(), commentText);
    }

    /**
     * Update a certain Comment
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apisApiIdCommentsCommentIdPutTest() throws ApiException {
        String commentId = UUID.randomUUID().toString();
        String apiId = response1.getId();
        String commentText = "This is a comment";
        String updatedCommentText = "This is the updated comment";
        String ifNoneMatch = null;
        String ifModifiedSince = null;
        String ifMatch = null;
        String ifUnmodifiedSince = null;

        Comment body = new Comment();
        body.setCommentId(commentId);
        body.setApiId(apiId);
        body.setUsername(response1.getProvider());
        body.setCommentText(commentText);

        Comment responseCommpentPost = api.apisApiIdCommentsPost(apiId, body);
        Comment responseCommentGet = api.apisApiIdCommentsCommentIdGet
                (responseCommpentPost.getCommentId(), apiId, ifNoneMatch, ifModifiedSince);

        Assert.assertEquals(responseCommentGet.getCommentText(), commentText);

        Comment bodyUpdated = new Comment();
        bodyUpdated.setCommentId(commentId);
        bodyUpdated.setApiId(apiId);
        bodyUpdated.setUsername(response1.getProvider());
        bodyUpdated.setCommentText(updatedCommentText);

        Comment response = api.apisApiIdCommentsCommentIdPut
                (responseCommentGet.getCommentId(), apiId, bodyUpdated, ifMatch, ifUnmodifiedSince);

        Assert.assertEquals(response.getCommentText(), updatedCommentText);
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apisApiIdCommentsPostTest() throws ApiException {
        String apiId = response1.getId();
        String commentText = "This is a comment";
        String commentId = UUID.randomUUID().toString();
        Comment body = new Comment();
        body.setCommentId(commentId);
        body.setApiId(apiId);
        body.setUsername(response1.getProvider());
        body.setCommentText(commentText);
        Comment response = api.apisApiIdCommentsPost(apiId, body);
        Assert.assertEquals(response.getUsername(), response1.getProvider());
        Assert.assertEquals(response.getCommentText(), commentText);
    }

    /**
     * Downloads a FILE type document/get the inline content or source url of a certain document.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apisApiIdDocumentsDocumentIdContentGetTest() throws ApiException {
        String apiId = null;
        String documentId = null;
        String ifNoneMatch = null;
        String ifModifiedSince = null;
        api.apisApiIdDocumentsDocumentIdContentGet(apiId, documentId, ifNoneMatch, ifModifiedSince);

        // TODO: test validations
    }

    /**
     * Get a particular document associated with an API.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apisApiIdDocumentsDocumentIdGetTest() throws ApiException {
        String apiId = null;
        String documentId = null;
        String ifNoneMatch = null;
        String ifModifiedSince = null;
        Document response = api.apisApiIdDocumentsDocumentIdGet(apiId, documentId, ifNoneMatch, ifModifiedSince);

        // TODO: test validations
    }

    /**
     * Get a list of documents belonging to an API.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apisApiIdDocumentsGetTest() throws ApiException {
        String apiId = null;
        Integer limit = null;
        Integer offset = null;
        String ifNoneMatch = null;
        DocumentList response = api.apisApiIdDocumentsGet(apiId, limit, offset, ifNoneMatch);

        // TODO: test validations
    }

    /**
     * Get details of an API
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apisApiIdGetTest() throws ApiException {
        String apiId = null;
        String ifNoneMatch = null;
        String ifModifiedSince = null;
        API response = api.apisApiIdGet(apiId, ifNoneMatch, ifModifiedSince);

        // TODO: test validations
    }

    /**
     * Get the rating of an API.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apisApiIdRatingsGetTest() throws ApiException {
        String apiId = null;
        Integer limit = null;
        Integer offset = null;
        RatingList response = api.apisApiIdRatingsGet(apiId, limit, offset);

        // TODO: test validations
    }

    /**
     * Get a specific rating of an API.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apisApiIdRatingsRatingIdGetTest() throws ApiException {
        String apiId = null;
        String ratingId = null;
        String ifNoneMatch = null;
        String ifModifiedSince = null;
        Rating response = api.apisApiIdRatingsRatingIdGet(apiId, ratingId, ifNoneMatch, ifModifiedSince);

        // TODO: test validations
    }

    /**
     * Get the swagger of an API
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apisApiIdSwaggerGetTest() throws ApiException {
        String apiId = null;
        String ifNoneMatch = null;
        String ifModifiedSince = null;
        api.apisApiIdSwaggerGet(apiId, ifNoneMatch, ifModifiedSince);

        // TODO: test validations
    }

    /**
     * Adds or updates a rating
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apisApiIdUserRatingPutTest() throws ApiException {
        String apiId = null;
        Rating body = null;
        Rating response = api.apisApiIdUserRatingPut(apiId, body);

        // TODO: test validations
    }

    /**
     * Get WSDL definition
     * <p>
     * This operation can be used to retrieve the swagger definition of an API.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apisApiIdWsdlGetTest() throws ApiException {
        String apiId = null;
        String labelName = null;
        String ifNoneMatch = null;
        String ifModifiedSince = null;
        api.apisApiIdWsdlGet(apiId, labelName, ifNoneMatch, ifModifiedSince);

        // TODO: test validations
    }

    @AfterClass
    public void afterClass() throws org.wso2.carbon.apimgt.rest.integration.tests.publisher.ApiException, InterruptedException {
        org.wso2.carbon.apimgt.rest.integration.tests.publisher.model.APIList response =
                apiSetup.apisGet(10, 0, null, null, null);
        apiRemove.apisApiIdDelete(response.getList().get(0).getId(), null, null);
    }
}
