/*
 * WSO2 API Manager - Store
 * This document specifies a **RESTful API** for WSO2 **API Manager** - Store.  It is written with [swagger 2](http://swagger.io/). 
 *
 * OpenAPI spec version: v1.0
 * Contact: architecture@wso2.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.wso2.carbon.apimgt.rest.integration.tests.store.api;

import org.testng.annotations.Test;
import org.wso2.carbon.apimgt.rest.integration.tests.store.ApiException;
import org.wso2.carbon.apimgt.rest.integration.tests.store.model.ApplicationList;

/**
 * API tests for ApplicationCollectionApi
 */
public class ApplicationCollectionApiTest {

    private final ApplicationCollectionApi api = new ApplicationCollectionApi();


    /**
     * Get a list of applications
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void applicationsGetTest() throws ApiException {
        String query = null;
        Integer limit = null;
        Integer offset = null;
        String ifNoneMatch = null;
        ApplicationList response = api.applicationsGet(query, limit, offset, ifNoneMatch);

        // TODO: test validations
    }

}
