/*
 * WSO2 API Manager - Store
 * This document specifies a **RESTful API** for WSO2 **API Manager** - Store.  It is written with [swagger 2](http://swagger.io/). 
 *
 * OpenAPI spec version: v1.0
 * Contact: architecture@wso2.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.wso2.carbon.apimgt.rest.integration.tests.store.api;

import org.testng.annotations.Test;
import org.wso2.carbon.apimgt.rest.integration.tests.store.ApiException;
import org.wso2.carbon.apimgt.rest.integration.tests.store.model.CommentList;

/**
 * API tests for CommentsCollectionApi
 */
public class CommentsCollectionApiTest {

    private final CommentsCollectionApi api = new CommentsCollectionApi();


    /**
     * Get a list of Comments that are already added to APIs
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apisApiIdCommentsGetTest() throws ApiException {
        String apiId = null;
        Integer limit = null;
        Integer offset = null;
        CommentList response = api.apisApiIdCommentsGet(apiId, limit, offset);

        // TODO: test validations
    }

}
