/*
 * WSO2 API Manager - Store
 * This document specifies a **RESTful API** for WSO2 **API Manager** - Store.  It is written with [swagger 2](http://swagger.io/). 
 *
 * OpenAPI spec version: v1.0
 * Contact: architecture@wso2.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.wso2.carbon.apimgt.rest.integration.tests.store.api;

import org.testng.annotations.Test;
import org.wso2.carbon.apimgt.rest.integration.tests.store.ApiException;

/**
 * API tests for DeleteApi
 */
public class DeleteApiTest {

    private final DeleteApi api = new DeleteApi();


    /**
     * Remove a Comment
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apisApiIdCommentsCommentIdDeleteTest() throws ApiException {
        String commentId = null;
        String apiId = null;
        String ifMatch = null;
        String ifUnmodifiedSince = null;
        api.apisApiIdCommentsCommentIdDelete(commentId, apiId, ifMatch, ifUnmodifiedSince);

        // TODO: test validations
    }

    /**
     * Remove an application
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void applicationsApplicationIdDeleteTest() throws ApiException {
        String applicationId = null;
        String ifMatch = null;
        String ifUnmodifiedSince = null;
        api.applicationsApplicationIdDelete(applicationId, ifMatch, ifUnmodifiedSince);

        // TODO: test validations
    }

    /**
     * Remove subscription
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void subscriptionsSubscriptionIdDeleteTest() throws ApiException {
        String subscriptionId = null;
        String ifMatch = null;
        String ifUnmodifiedSince = null;
        api.subscriptionsSubscriptionIdDelete(subscriptionId, ifMatch, ifUnmodifiedSince);

        // TODO: test validations
    }

}
