/*
 * WSO2 API Manager - Store
 * This document specifies a **RESTful API** for WSO2 **API Manager** - Store.  It is written with [swagger 2](http://swagger.io/). 
 *
 * OpenAPI spec version: v1.0
 * Contact: architecture@wso2.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.wso2.carbon.apimgt.rest.integration.tests.store.api;

import org.testng.annotations.Test;
import org.wso2.carbon.apimgt.rest.integration.tests.store.ApiException;
import org.wso2.carbon.apimgt.rest.integration.tests.store.model.ApplicationToken;
import org.wso2.carbon.apimgt.rest.integration.tests.store.model.ApplicationTokenGenerateRequest;

/**
 * API tests for GenerateApplicationTokenApi
 */
public class GenerateApplicationTokenApiTest {

    private final GenerateApplicationTokenApi api = new GenerateApplicationTokenApi();


    /**
     * Generate an access token for application by client_credentials grant type
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void applicationsApplicationIdGenerateTokenPostTest() throws ApiException {
        String applicationId = null;
        ApplicationTokenGenerateRequest body = null;
        String ifMatch = null;
        String ifUnmodifiedSince = null;
        ApplicationToken response = api.applicationsApplicationIdGenerateTokenPost(applicationId, body, ifMatch, ifUnmodifiedSince);

        // TODO: test validations
    }

}
