/*
 * WSO2 API Manager - Store
 * This document specifies a **RESTful API** for WSO2 **API Manager** - Store.  It is written with [swagger 2](http://swagger.io/). 
 *
 * OpenAPI spec version: v1.0
 * Contact: architecture@wso2.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.wso2.carbon.apimgt.rest.integration.tests.store.api;

import org.testng.annotations.Test;
import org.wso2.carbon.apimgt.rest.integration.tests.store.ApiException;
import org.wso2.carbon.apimgt.rest.integration.tests.store.model.ApplicationKeyGenerateRequest;
import org.wso2.carbon.apimgt.rest.integration.tests.store.model.ApplicationKeys;

/**
 * API tests for GenerateKeysApi
 */
public class GenerateKeysApiTest {

    private final GenerateKeysApi api = new GenerateKeysApi();


    /**
     * Generate keys (Consumer key/secret) for application
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void applicationsApplicationIdGenerateKeysPostTest() throws ApiException {
        String applicationId = null;
        ApplicationKeyGenerateRequest body = null;
        ApplicationKeys response = api.applicationsApplicationIdGenerateKeysPost(applicationId, body);

        // TODO: test validations
    }

}
