/*
 * WSO2 API Manager - Store
 * This document specifies a **RESTful API** for WSO2 **API Manager** - Store.  It is written with [swagger 2](http://swagger.io/). 
 *
 * OpenAPI spec version: v1.0
 * Contact: architecture@wso2.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.wso2.carbon.apimgt.rest.integration.tests.store.api;

import org.testng.annotations.Test;
import org.wso2.carbon.apimgt.rest.integration.tests.store.ApiException;
import org.wso2.carbon.apimgt.rest.integration.tests.store.model.Application;
import org.wso2.carbon.apimgt.rest.integration.tests.store.model.Comment;

/**
 * API tests for UpdateApi
 */
public class UpdateApiTest {

    private final UpdateApi api = new UpdateApi();


    /**
     * Update a certain Comment
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apisApiIdCommentsCommentIdPutTest() throws ApiException {
        String commentId = null;
        String apiId = null;
        Comment body = null;
        String ifMatch = null;
        String ifUnmodifiedSince = null;
        Comment response = api.apisApiIdCommentsCommentIdPut(commentId, apiId, body, ifMatch, ifUnmodifiedSince);

        // TODO: test validations
    }

    /**
     * Update application details
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void applicationsApplicationIdPutTest() throws ApiException {
        String applicationId = null;
        Application body = null;
        String ifMatch = null;
        String ifUnmodifiedSince = null;
        Application response = api.applicationsApplicationIdPut(applicationId, body, ifMatch, ifUnmodifiedSince);

        // TODO: test validations
    }

}
