/*
 * WSO2 API Manager - Store
 * This document specifies a **RESTful API** for WSO2 **API Manager** - Store.  It is written with [swagger 2](http://swagger.io/). 
 *
 * OpenAPI spec version: v1.0
 * Contact: architecture@wso2.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.wso2.carbon.apimgt.rest.integration.tests.store.api;

import org.testng.annotations.Test;
import org.wso2.carbon.apimgt.rest.integration.tests.store.ApiException;
import org.wso2.carbon.apimgt.rest.integration.tests.store.model.Workflow;
import org.wso2.carbon.apimgt.rest.integration.tests.store.model.WorkflowResponse;

/**
 * API tests for WorkflowsIndividualApi
 */
public class WorkflowsIndividualApiTest {

    private final WorkflowsIndividualApi api = new WorkflowsIndividualApi();


    /**
     * Update workflow status
     * <p>
     * This operation can be used to approve or reject a workflow task. .
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void workflowsWorkflowReferenceIdPutTest() throws ApiException {
        String workflowReferenceId = null;
        Workflow body = null;
        WorkflowResponse response = api.workflowsWorkflowReferenceIdPut(workflowReferenceId, body);

        // TODO: test validations
    }

}
